- name: Download Elastisearch 
  shell:
    sudo wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb

- name: Install Transport HTTPs
  apt:
    name:
      - apt-transport-https
    state: latest
    update_cache: true

- name: Install Elasticsearch
  shell:
    sudo dpkg -i elasticsearch-7.6.2-amd64.deb

- name: Update Elasticsearch Default
  shell:
    sudo update-rc.d elasticsearch defaults 95 10

- name: Restart Elasticsearch
  become: yes
  service: 
    name: elasticsearch 
    state: restarted 